extern crate cbindgen;

fn generate_c_header() {
    let crate_dir: String = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_file: &str = "generated/include/libargon2_rust.h";
    
    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("argon2_rust_h")
        .with_autogen_warning(
            "/* This file is automatically generated. Do not edit directly. */"
        )
        .with_namespace("argon2_rust")
        .generate()
        .expect("Unable to generate C header")
        .write_to_file(output_file);
}

fn main() {
    // Instruct Cargo to rerun the build script if src/lib.rs changes
    println!("cargo:rerun-if-changed=src/lib.rs");
    
    if std::env::var("CARGO_CFG_CLIPPY").is_err() {
        // Only run cbindgen when not running clippy
        extern crate cbindgen;
        generate_c_header();
    }
}